In [1]:
import numpy as np

identity_matrix = np.eye(4)

print("4x4 Identity Matrix:")
print(identity_matrix)

4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
import numpy as np

# Generate two 3x3 matrices with random integers (1 to 9)
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Addition
add = A + B
print("\nAddition (A + B):")
print(add)

# Multiplication
mul = np.dot(A, B)
print("\nMultiplication (A × B):")
print(mul)

Matrix A:
[[2 1 5]
 [9 4 6]
 [2 6 7]]

Matrix B:
[[9 1 5]
 [2 9 7]
 [7 5 9]]

Addition (A + B):
[[11  2 10]
 [11 13 13]
 [ 9 11 16]]

Multiplication (A × B):
[[ 55  36  62]
 [131  75 127]
 [ 79  91 115]]


In [6]:
import numpy as np

print("Enter elements for 5x3 matrix:")

A = []
for i in range(5):
    row = list(map(int, input(f"Row {i+1}: ").split()))
    A.append(row)

A = np.array(A)

print("\nEnter elements for 3x2 matrix:")

B = []
for i in range(3):
    row = list(map(int, input(f"Row {i+1}: ").split()))
    B.append(row)

B = np.array(B)

# Multiply matrices
result = np.dot(A, B)

print("\nProduct Matrix (5x2):")
print(result)

Enter elements for 5x3 matrix:
Row 1: 2 4 5
Row 2: 3 5 6
Row 3: 5 3 1 
Row 4: 7 8 5
Row 5: 2 3 4

Enter elements for 3x2 matrix:
Row 1: 3 2 
Row 2: 6 88
Row 3: 3 2

Product Matrix (5x2):
[[ 45 366]
 [ 57 458]
 [ 36 276]
 [ 84 728]
 [ 36 276]]
